_BASE_: ../Base-ADE20K-Full-SemanticSegmentation.yaml
MODEL:
  META_ARCHITECTURE: "SemanticSegmentor"
  RESNETS:
    DEPTH: 50
    NORM: "SyncBN"
    OUT_FEATURES: ["res2", "res5"]
    RES5_MULTI_GRID: [1, 2, 4]
    STRIDE_IN_1X1: False
    RES5_DILATION: 2
  SEM_SEG_HEAD:
    NAME: "DeepLabV3PlusHead"
    IGNORE_VALUE: 65535
    IN_FEATURES: ["res2", "res5"]
    ASPP_CHANNELS: 256
    ASPP_DILATIONS: [6, 12, 18]
    ASPP_DROPOUT: 0.1
    CONVS_DIM: 256
    NUM_CLASSES: 847
    LOSS_TYPE: "hard_pixel_mining"
    PROJECT_FEATURES: ["res2"]
    PROJECT_CHANNELS: [48]
    NORM: "SyncBN"
    COMMON_STRIDE: 4
SOLVER:
  OPTIMIZER: "SGD"
  BASE_LR: 0.01
  MAX_ITER: 200000  # ~120 epcoch
  BACKBONE_MULTIPLIER: 1.0
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  IMS_PER_BATCH: 16
TEST:
  EVAL_PERIOD: 10000
  AUG:
    ENABLED: False
    MIN_SIZES: [256, 384, 512, 640, 768, 896]
    MAX_SIZE: 3584
    FLIP: True
