_BASE_: maskformer2_SwinL_bs16_200k.yaml
OUTPUT_DIR: training_dir/ade20k-full_swinl_bs8_400k/
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.00005
  MAX_ITER: 400000  # ~120 epcoch
TEST:
  EVAL_PERIOD: 20000