_BASE_: maskformer2_R50_bs16_200k.yaml
OUTPUT_DIR: training_dir/ade20k-full_rfs_r50_bs16_200k/
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler_Seg"
  FREQUENCY_TYPE: "image" # image / pixel / pixel_ratio
  REPEAT_THRESHOLD: 0.0003
  ANN_TYPE: "seg"
  REPEAT_FACTOR_FILE: "datasets/ade20k-full_rf"