_BASE_: maskformer2_R50_bs16_160k.yaml
MODEL:
  WEIGHTS: "R-101.pkl"  # torchvision .pth convert
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: False
    NORM: "SyncBN"  # use syncbn follow mask2former
